#!/bin/bash
pwd=`pwd`
if [ "$(id -u)" == "0" ]; then
	$pwd/scripts/install.sh $1
else
	echo "You need to execute as root. Use: sudo ./install (Necessário executar como root. Utilize: sudo ./install)"
fi
