#!/bin/bash
pwd=`pwd`

if [ "$(id -u)" == "0" ]; then
        $pwd/scripts/uninstall.sh
else
        echo "You need to execute as root. Use: sudo ./uninstall (Necessário executar como root. Utilize: sudo ./uninstall)"
fi

